rails_project/config/routes.rb
Rails.application.routes.draw do

  #home page
  root 'application#home'

  #custom routes
    #register routes
    get '/register', to: 'users#new'
    post '/register', to: 'users#create'

    #login routes
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'

    #omniauth routes
    get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

    #logout routes
    delete '/logout', to: 'sessions#destroy'


  resources :users do
    resources :jobs
  end

  resources :jobs do
    resources :tools
  end

  resources :tools

end

rails_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_project/app/models/job.rb
class Job < ApplicationRecord
    belongs_to :user
    has_many :tools
    has_many :users, through: :tools

    validates :title, presence: true
    
    scope :alpha, -> {order('LOWER(title)')}
end

rails_project/app/models/tool.rb
class Tool < ApplicationRecord
    belongs_to :user
    belongs_to :job

    validates :title, presence: true
end

rails_project/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :jobs
    has_many :tools
    has_many :rec_tools, through: :tools, source: :job

    validates :email, presence: true, uniqueness: true
    validates :password, presence: true

end

rails_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    private

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!session[:user_id]
    end

    def redirect
        if !logged_in?
            redirect_to root_path
        end
    end

end

rails_project/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :redirect

    def new
        @job = Job.new
    end

    def create
        @job = current_user.jobs.build(job_params)
        if @job.save
            redirect_to job_path(@job)
        else
            @error = @job.errors.full_messages
            render :new
        end
    end

    def edit
        @job = Job.find(params[:id])
    end

    def update
        @job = Job.find(params[:id])
        @job.update(job_params)
        redirect_to job_path
    end

    def destroy
        @job = Job.find(params[:id])
        @job.tools.each do |t|
            t.destroy
        end
        @job.destroy
        redirect_to jobs_path
    end

    def index
        @jobs = Job.alpha.all
    end

    def show
        @job = Job.find_by_id(params[:id])
        @tool = Tool.find_by_id(params[:id])
    end


    private

    def job_params
        params.require(:job).permit(:title, :content)
    end
end

rails_project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        user = User.find_by(email: params[:user][:email])
        if user && user.authenticate(params[:user][:password]) 
            session[:user_id] = user.id #helps app remember user is logged in
            redirect_to user_path(user)
        else
            flash[:message] = 'Invalid login'
            redirect_to '/login'
        end
    end

    def omniauth
        @user = User.find_or_create_by(email: auth['info']['email']) do |user|
            user.password = SecureRandom.hex
        end
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            redirect_to root_path
        end
    end

    def destroy
        reset_session
        redirect_to root_path
    end

    private

    #used to get info about google account
    def auth
        request.env['omniauth.auth']
    end

end

rails_project/app/controllers/tools_controller.rb
class ToolsController < ApplicationController
    before_action :redirect

    def new
        if params[:job_id] && @job = Job.find_by_id(params[:job_id])
        @tool = @job.tools.new
        end
    end

    def create
        @job = Job.find(params[:tool][:job_id])
        @tool = current_user.tools.new(tool_params)

        if @tool.save
            redirect_to job_path(@job)
        else
            @error = 'Tool must include a name'
            render :new
        end
    end

    private

    def tool_params
        params.require(:tool).permit(:title, :job_id, :user_id)
    end

end

rails_project/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            @error = @user.errors.full_messages
            render :new
        end
    end

    def show
        redirect
        @user = User.find_by_id(params[:id])
        redirect_to root_path if !@user
    end

    private

    def user_params
        params.require(:user).permit(:email, :password)
    end

end

rails_project/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_project/app/helpers/job_tools_helper.rb
module JobToolsHelper
end

rails_project/app/helpers/jobs_helper.rb
module JobsHelper
end

rails_project/app/helpers/sessions_helper.rb
module SessionsHelper
end

rails_project/app/helpers/tools_helper.rb
module ToolsHelper
end

rails_project/app/helpers/users_helper.rb
module UsersHelper
end

rails_project/app/views/application/home.html.erb
<h1>Job Manager</h1>

rails_project/app/views/jobs/_form.html.erb
<%= form_for(job) do |f|%>

    <%= f.label :title %>
    <%= f.text_field :title %>
<br>
    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.submit 'Submit'%>

<%end%>

rails_project/app/views/jobs/edit.html.erb
<h1>Edit Job</h1>

<%= render 'form', job: @job%>

rails_project/app/views/jobs/index.html.erb
<h1>All Current Jobs</h1>

<% @jobs.each do |job| %>
    <p>
    <strong><%= link_to job.title, job_path(job) %></strong> 
    by <strong><%= job.user.email%></strong>
<%end%>

<h2>Jobs you have recommended tools for:</h2>
    <p>
    <% current_user.rec_tools.each do |job| %>
    <strong><%= link_to job.title, job_path(job) %></strong> 
    by <strong><%= job.user.email%></strong>
    <br>
    <strong>Rec. tool count:</strong> (<%=job.tools.count%>)
    <br>
    </p>
<%end%>

rails_project/app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= @error%>

<p>
<%= render 'form', job: @job%>
</p>

rails_project/app/views/jobs/show.html.erb
<h1><%= @job.title%> by <%=@job.user.email%></h1>

<p><strong>Details:</strong> <%= @job.content%></p>

<p><strong>Tool list:</strong></p>
    <ul>
        <% @job.user.tools.each do |t| if t.job_id == @job.id%>
       
            <li>   
                <strong><%= t.title %></strong> added by <strong><%= t.user.email %></strong>
            </li>
            <%end%>
        <%end%>
    </ul>

    <p><strong>Recommended tool list:</strong></p>
    <ul>
        <% @job.tools.each do |t| if t.user_id == @job.user_id%>
            <%yield%>
            <%else%>
                <li>   
                    <strong><%= t.title %></strong> recommended by <%= t.user.email %>
                </li>
            <%end%>
        <%end%>
    </ul>

<% if @job.user == current_user%>
    <%= link_to 'Add tools', new_job_tool_path(@job)%> |
    <%= link_to 'Edit Job', edit_user_job_path(@job.user, @job)%> |
    <%= link_to 'Delete Job', job_path(@job), method: :delete %>
    <%else%>
    <%= link_to 'Recommend tool', new_job_tool_path(@job)%>
<%end%>

rails_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav>
    <% if logged_in?%>
    Logged in as: <%= current_user.email%>
    <br>
    <%= link_to 'New Job', new_job_path%> |
    <%= link_to 'Jobs', jobs_path%> |
    <%= link_to 'Logout', logout_path, method:'delete'%>
    <%else%>
    <%= link_to 'Register', register_path%> |
    <%= link_to 'Login', login_path%> |
    <%= link_to 'Login with Google', '/auth/google_oauth2'%>
    <%end%>
    </nav>

    <%= yield %>
  </body>
</html>

rails_project/app/views/tools/new.html.erb
<h1>New Tool</h1>

<%= @error%>

<%= form_for(@tool) do |f|%>
<%= f.hidden_field :job_id, :value => @job.id %>
<p>
    <%= f.label :title, 'Tool name:' %>
    <%= f.text_field :title %>

    <%= f.submit 'Submit'%>
</p>

<%end%>

rails_project/app/views/users/new.html.erb
<h1>Register</h1>
<%= @error%>

<%= form_for(@user) do |f|%>

    <%= f.label :email %>
    <%= f.email_field :email %>
<br>
    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit 'Submit'%>

<%end%>

rails_project/app/views/users/show.html.erb
<h1>Job Manager</h1>

<div>Welcome to Job Manager.</div>

<div>
<br>Start a new job by selecting "New Job" in the navigation bar or
<br>see a list of all current jobs by selecting "Jobs".
</div>